# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPr7YkugG51UWK_Xg-Y6-6ieRkfNePtZ
"""

import pandas as pd

# read in the two Excel sheets as dataframes
df1 = pd.read_excel("Apps Missing CEEB Code.xlsx")
df2 = pd.read_excel("CEEB Codes to Add or Update.xlsx")

# create an empty list to store the missing records
missing_records = []

# loop through each row in df1
for index, row in df1.iterrows():
    # check if the row exists in df2
    if not df2[df2['M Number'] == row['M Number']].empty:
        continue
    # if the row is not in df2, add it to the missing_records list
    missing_records.append(row)

# create a new dataframe from the missing_records list
missing_records_df = pd.DataFrame(missing_records)

# output the missing records to a new Excel sheet
missing_records_df.to_excel("missing_records.xlsx", index=False)